export const URLS = [
  { group: "Default", label: "Home page", url: "https://www.shoplc.com/" },
  { group: "Cane", label: "Cane — Landing", url: "https://www.shoplc.com/pages/cane" },
  { group: "Cane", label: "Cane — LP002", url: "https://www.shoplc.com/pages/cane-lp002" },
  { group: "SoulSmart Cane", label: "SoulSmart Cane — Overview", url: "https://www.shoplc.com/pages/soulsmart-foldable-walking-cane-with-led" },
  { group: "SoulSmart Cane", label: "SoulSmart Cane — Product (Landing view)", url: "https://www.shoplc.com/products/soulsmart-black-2-handles-foldable-smart-easy-up-cane-with-led-light-2xaaa-batteries-not-included?view=landing" },
  { group: "SoulSmart Cane", label: "SoulSmart Cane — Independence", url: "https://www.shoplc.com/pages/soulsmart-give-them-more-independence" },
  { group: "LivMore Stepper", label: "LivMore Stepper — Product (Landing)", url: "https://www.shoplc.com/products/livmore-red-under-desk-electric-stepper-with-lcd-display?view=landing" },
  { group: "LivMore Stepper", label: "LivMore Stepper — v5", url: "https://www.shoplc.com/pages/livmore-black-electric-stepper-v5" },
  { group: "LivMore Stepper", label: "LivMore Stepper — Favorite Chair", url: "https://www.shoplc.com/pages/livmore-stepper-favorite-chair-listicle" },
  { group: "LivMore Stepper", label: "LivMore Stepper — Swelling At Night", url: "https://www.shoplc.com/pages/livmore-stepper-swelling-nightfall" },
  { group: "LivMore Stepper", label: "LivMore Stepper — 6 Reasons", url: "https://www.shoplc.com/pages/livmore-stepper-6-reasons-when-walking-hurts" },
  { group: "Auctions", label: "Online Auctions — TSL", url: "https://www.shoplc.com/pages/online-auctions-tsl" },
  { group: "Luxuriant LGD Earring", label: "Luxuriant Earring — Base", url: "https://www.shoplc.com/products/luxuriant-lab-grown-diamond-earring-in-18k-yg-vermeilsterling-silver-0-50-ctw?variant=52279301865785" },
  { group: "Luxuriant LGD Earring", label: "Luxuriant Earring — Flat Back v2", url: "https://www.shoplc.com/products/luxuriant-lab-grown-diamond-earring-in-18k-yg-vermeilsterling-silver-0-50-ctw?view=flat-back-lgd-v2" },
  { group: "Luxuriant LGD Earring", label: "Flat Back Diamond — All-Day Comfort", url: "https://www.shoplc.com/pages/all-day-comfort-flat-back-diamond-listicle" },
  { group: "Luxuriant LGD Earring", label: "Flat Back Diamond — Less Worry", url: "https://www.shoplc.com/pages/everyday-diamonds-less-worry-listicle" },
  { group: "Luxuriant LGD Earring", label: "Flat Back Diamond — Side Sleeper", url: "https://www.shoplc.com/pages/side-sleeper-flat-back-diamond-listicle" },
  { group: "Luxuriant LGD Earring", label: "Luxuriant Earring — Flat Back LP v2", url: "https://www.shoplc.com/products/luxuriant-lab-grown-diamond-earring-in-18k-yg-vermeilsterling-silver-0-50-ctw?view=flat-back-lp-v2" },
  { group: "Luxuriant LGD Earring", label: "Luxuriant Earring — Iceglass Studs", url: "https://www.shoplc.com/products/luxuriant-lab-grown-diamond-earring-in-18k-yg-vermeilsterling-silver-0-50-ctw?view=flatback-studs-iceglass&variant=54279795507513" },
  { group: "Gold Sheets", label: "Gold Sheets — Embossed v2", url: "https://www.shoplc.com/collections/gold-embossed-sheets-v2" },
  { group: "Gold Sheets", label: "Gold Sheets — Lunar Zodiac", url: "https://www.shoplc.com/collections/gold-sheet-zodiac-page/lunar-zodiac" },
  { group: "Gold Sheets", label: "Gold Sheets — Patriotic", url: "https://www.shoplc.com/collections/gold-sheet-patriotic" },
  { group: "Gold Sheets", label: "Gold Sheets — LP v1", url: "https://www.shoplc.com/pages/gold-sheet-lp-v1" },
  { group: "Gold Sheets", label: "Gold Sheets — Listicle", url: "https://www.shoplc.com/collections/gold-sheet-listicle" },
  { group: "LGD Meta 2026", label: "LGD Meta 2026 — v2", url: "https://www.shoplc.com/collections/lgd-meta-2026?view=lgd-v2" },
  { group: "Topaz Ring", label: "D-Joy Topaz Ring", url: "https://www.shoplc.com/products/d-joy-asscher-cut-white-topaz-ring-in-14k-yg-over-sterling-silver-size-4-0-1-35-ctw?variant=54193828954425" },
];

export const WINDOW_DAYS = 15;
